### PR TITLE
a new localization solution , process all .json file as content

### PR DESCRIPTION
**Pull request by jkjhcl**

### CODE REVIEW

**Comment by testradav** [comment]
@mikeangelsilva  is this mergeable?  will this break current hikes if we merge now?  I don't want to introduce i18n changes into this release branch (risk)

**Comment by mikeangelsilva** [comment]
> @mikeangelsilva is this mergeable? will this break current hikes if we merge now? I don't want to introduce i18n changes into this release branch (risk)

lets hold it off for now. this will break the flow of hikes(urls, paramets, etc) and will affect the Iris application.

**Comment by testradav** [comment]
> > @mikeangelsilva is this mergeable? will this break current hikes if we merge now? I don't want to introduce i18n changes into this release branch (risk)
> 
> let's hold it off for now. this will break the flow of hikes(urls, paramets, etc) and will affect the Iris application.

converted to draft and added DNM label
we should use a `l10n` (localization) branch then off of phx-dev

**Review by testradav — CHANGES_REQUESTED** [review]
@jkjhcl

please PR this against i10n branch so that we don't break phx-dev which is slated for Q2 release

**Comment by mikeangelsilva** [comment]
closing this one @jkjhcl  @testradav

**Pull request closed without merging**
