### PR TITLE
actualize l10n <- master

### PR DESCRIPTION
**Pull request by testradav**
## Description

PR to actualize L10N from master (master has phx-dev already).  Not sure if change is good though

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by testradav** [comment]
@mikeangelsilva @yanji-hcl not sure if this PR is useful but I figure at one point L10N probably wants to sync up with phx-dev or master

**Comment by yanji-hcl** [comment]
> @mikeangelsilva @yanji-hcl not sure if this PR is useful but I figure at one point L10N probably wants to sync up with phx-dev or master

Which branch should we use to export content to gh-pages? Is master branch or phx-dev branch?

**Comment by mikeangelsilva** [comment]
@yanji-hcl we use master branch by default. The github actions is set to master branch only.

**Comment by yanji-hcl** [comment]
> @yanji-hcl we use master branch by default. The github actions is set to master branch only.

OK, I'll try to fix the merge conflict once the all hikes contents issue are fixed.

**Comment by testradav** [comment]
@yanji-hcl is this PR now obsolete due to #48 ? or should this still be merged?

**Comment by yanji-hcl** [comment]
> @yanji-hcl is this PR now obsolete due to #48 ? or should this still be merged?

Now l10n is synced with phx-dev branch. Do we need to merge l10n into master branch? Is it right time for us to deliver localization feature?

**Comment by mikeangelsilva** [comment]
i think we can close this one since l10n has all the changes from phx-dev and master already has phx-dev changes.

**Comment by testradav** [comment]
> Now l10n is synced with phx-dev branch. Do we need to merge l10n into master branch? Is it right time for us to deliver localization feature?

L10N would need to go -> phx-dev and phx-dev -> master  ** but not until after 9.2 ships and needs to be coordinated with Sowri/Mahesh ** as it needs to be determined if hikes moves forward in sync with 9.3 releases or decoupled from Volt MX release timeframes

**Pull request closed without merging**
