### PR TITLE
wash SampleCSV

### PR DESCRIPTION
**Pull request by mikeangelsilva**
## Description
- wash email and password

Screenshot:

before:
image

after:
image

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Review by mandeepalluru — COMMENTED** [review]
@mikeangelsilva Would you mind posting a screenshot or details of the washing that has been performed.

**Comment by fuyi-li** [comment]
@mikeangelsilva , can you also pls include the link to the jira ticket

**Comment by mikeangelsilva** [comment]
pr updated.

**Comment by mandeepalluru** [comment]
@mikeangelsilva I just wanted to confirm on the discrepancy in washing "temenos" as shown below.
john.doe@temenos.com -> john.doe@woodburn.com
Temenos@123 -> VoltMX@123

**Comment by fuyi-li** [comment]
> @mikeangelsilva I just wanted to confirm on the discrepancy in washing "temenos" as shown below. [john.doe@temenos.com](mailto:john.doe@temenos.com) -> [john.doe@woodburn.com](mailto:john.doe@woodburn.com) Temenos@123 -> VoltMX@123

@mandeepalluru , yes, see screenshot above.

**Comment by mandeepalluru** [comment]
> > @mikeangelsilva I just wanted to confirm on the discrepancy in washing "temenos" as shown below. [john.doe@temenos.com](mailto:john.doe@temenos.com) -> [john.doe@woodburn.com](mailto:john.doe@woodburn.com) Temenos@123 -> VoltMX@123
> 
> @mandeepalluru , yes, see screenshot above.

@fuyi-li I was seeking confirmation on whether the discrepancy in washing Temenos to two different values (woodburn, VoltMX) is fine.

**Comment by fuyi-li** [comment]
@mandeepalluru , it would be @shant-hcl 's decision to use woodburn vs VoltMX. If we decided to use. VoltMX as opposed to woodburn, then the hikes card need to be updated as well. @shant-hcl , please confirm which way you want to go.

**Review by shant-hcl — APPROVED** [review]
Approved

**Pull request merged**
