### PR TITLE
IntroductiontoSegmentTemplatesV9

### PR DESCRIPTION
**Pull request by ArchanaWable**
## Description

Introduction to Segment - "s" is missing

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

HPHX-12447-C11 Before

HPHX-12447-C11

HPHX-12447-C11 After
MicrosoftTeams-image (6)

### CODE REVIEW

**Comment by mandeepalluru** [comment]
@ArchanaWable Is this the only fix to be made in this hike. Please confirm.
If the answer is no, then recommend you to have all fixes for a given hike in one PR.

**Comment by mandeepalluru** [comment]
@ArchanaWable Please add details of the Jira ticket.

**Comment by mandeepalluru** [comment]
Please add screenshots of before change and after change.

**Comment by ArchanaWable** [comment]
Checksum only need to uploaded.

**Pull request closed without merging**
